load("@doxygen//:doxygen.bzl", "doxygen")
load("@greet_generator//:defs.bzl", "generate_greeting")
load("@rules_cc//cc:defs.bzl", "cc_library")
load(":defs.bzl", "ext_and_gen_doxygen_rule")

cc_library(
    name = "add",
    srcs = ["add.cpp"],
    hdrs = ["add.h"],
)

cc_library(
    name = "sub",
    srcs = ["sub.cpp"],
    hdrs = ["sub.h"],
)

cc_library(
    name = "lib",
    hdrs = ["lib.h"],
    deps = [
        ":add",
        ":sub",
    ],
)

generate_greeting(
    name = "greet",
    greeting = "Hello world!",
    greeting_version = 42,
    strip_include_prefix = "//dependencies",
)

cc_library(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        ":greet",
        ":lib",
        "@greet_generator//:greet_api",
    ],
)

genrule(
    name = "section",
    outs = ["Section.md"],
    cmd = """
        echo "# Section " > $@
        echo "This is some amazing documentation with section!!  " >> $@
        echo "Incredible." >> $@
    """,
)

doxygen(
    name = "doxygen",
    srcs = [
        "README.md",  # file
        ":section",  # genrule
    ],
    project_brief = "Example project for doxygen",
    project_name = "dependencies",
    use_mdfile_as_mainpage = "dependencies/README.md",
    deps = [":main"],  # cc_library
)

# This demonstrates using a custom aspect and rule to also document external and generated source files.
# See defs.bzl for the custom aspect and rule construction.
doxygen(
    name = "doxygen_ext_and_gen",
    srcs = [
        "README.md",  # file
        ":section",  # genrule
    ],
    outs = [
        "ext_and_gen/html",
        "ext_and_gen/tags",
    ],
    doxyfile_prefix = "ext_and_gen",
    doxygen_rule = ext_and_gen_doxygen_rule,
    project_brief = "Example project for doxygen",
    project_name = "dependencies",
    use_mdfile_as_mainpage = "dependencies/README.md",
    deps = [":main"],  # cc_library
)
